dependencies:
  build:
    - node:14.0.0
    - yarn:1.22.4
    - python:2.7.18
  runtime:
    - node:14.0.0
    - yarn:1.22.4

build_targets:
  - name: default
    commands:
      - yarn install
    environment:
      - NODE_ENV=development
  - name: deploy
    commands:
      - yarn install
      - echo "Cannot deploy with a dirty working directory. If the next command errors, commit or stash changes then try again."
      - git diff --cached --exit-code
      - git checkout gh-pages
      - git -c "user.name=YourBase" -c "user.email=ben@yourbase.io" merge --no-ff --no-edit --allow-unrelated-histories -s recursive -Xtheirs master
      - yarn build
      - mv dist/* .
      - git -c "user.name=Yourbase" -c "user.email=ben@yourbase.io" commit --all --message 'Automatic build by YourBase'
      - git prune
      - git push
      - git checkout master
    environment:
      - NODE_ENV=production

exec:
  commands:
    - npm rebuild node-sass
    - yarn serve
  environment:
    default:
      - NODE_ENV=development
  image: nodejs:latest
  ports:
    - 8080

ci:
  builds:
    - name: default
      build_target: default
