dependencies:
  build:
    - node:13.14.0
    - yarn:1.22.4
  runtime:
    - node:13.14.0
    - yarn:1.22.4

build_targets:
  - name: default
    commands:
      - yarn install
    environment:
      - NODE_ENV=development
  - name: deploy
    commands:
      - ./.yourbase_deploy.sh
    environment:
      - NODE_ENV=production

exec:
  commands:
    - npm rebuild node-sass
    - yarn serve
  environment:
    default:
      - NODE_ENV=development
  image: nodejs:latest
  ports:
    - 8080

ci:
  builds:
    - name: build
      build_target: default
    - name: deploy
      build_target: deploy
      when: branch is 'master'
