#+CATEGORY: living document
#+DATE: 2023-02-16
#+FILENAME: now.html
#+TYPE: post

/This page is in the form of [[https://sive.rs/now][Derek Sivers's =/now= page]]./

* What I'm Doing Now

** SunPower

Since July 2022 I've worked at [[https://sunpower.com][SunPower]], a consumer solar panel
company serving the US. I worked for six months on a team that manages
the data pipeline between panels and the consumer mobile app.

I jumped in February 2023 to a new team spun up to reimagine the
customer onboarding pipeline that takes place between someone saying
"I would like some panels please" and actually getting the panels
bolted to their roof. This is a complex process involving permitting,
panel placement design, electrical work, and shipping the right parts
to the right place, among sometimes-exceptional circumstances like
roof replacement.

The team's goal is to take this process from the current ~months down
to ~days. It involves a lot of learning and has been super fun so
far. I'm working with two people who are also ex-[[https://twitch.tv][Twitch]], which has
been a fun bonding experience.

** Emacs

I've started using Emacs and org-mode. Both are great and it really
feels like Emacs : Vim :: Vim : nano. It's pretty rocky here and there
but I can feel the power lurking under the surface. Time will tell if
the rocks eventually erode my motivation and I jump back to VSCode
again, as I tended to do on six-month rotations between Vim and
VSCode.

** This Website

Somehow after a dozen attempts over two dozen years I finally have a
website that I've stuck with for quite a while. The secret sauce
turned out to be building the generator myself, because I constantly
want to try some new way of writing and this is the only way I can be
sure I have the context to implement it. For example, [[https://github.com/glacials/twos.dev/blob/main/src/cold/now.org][this page itself]]
is written in org-mode automatically converted from Org to HTML at
build-time.

(For more information see [[/meta.html][Inside twos.dev]], or the [[/winter][documentation]] for
the generator.)

** Autism

I found out in 2020 that I'm autistic and it's been a fantastic and
eye-opening experience. Every ~month (at first every ~day) I learn
that some weird behavior about myself is attributable to autism, and
that there's a pool of people I can talk to about it. These vary from
having been mute for 9 years as a child, to spending multiple hours
per day preparing and retrospecting conversations I've had, to not
liking hot weather, to sometimes feeling like every little noise is
far too loud.

I wrote about it in an article titled [[/autism.html][Anonymously Autistic]].

** Mastodon

I've mostly jumped ship from Twitter and have switched to Mastodon:
[[https://m.twos.dev/@ben][@ben@m.twos.dev]]. I run my own instance with signups closed just
because I wanted something to tinker with at the time.
